# Generated by Django 5.1.5 on 2025-01-29 12:43

import apps.general.service
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('juridic', 'Juridic'), ('physical', 'Physical')], default='juridic', max_length=25)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid first name.', regex='^[\\w.@+-]+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid last name.', regex='^[\\w.@+-]+$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.general.service.user_photo_location)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number', regex='^\\+998\\d{9}$')])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('role', models.CharField(choices=[('sponsor', 'Sponsor'), ('student', 'Student'), ('admin', 'Admin')], max_length=10)),
                ('student_degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('empty', 'Empty')], default='empty', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.university')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
