# Generated by Django 5.1.6 on 2025-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('juridic', 'Juridic'), ('physical', 'Physical'), ('empty', 'Empty')], default='empty', max_length=25),
        ),
    ]
