# Generated by Django 5.1.5 on 2025-01-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'sponsor'}, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
