# Generated by Django 5.1.5 on 2025-01-29 12:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Enter the amount money', max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(help_text='Enter lake this Call number +998 99 999 99 99', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number', regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('new', 'New'), ('moderated', 'Moderated'), ('verified', 'Verified')], default='new', max_length=25)),
                ('full_name', models.CharField(help_text='Please enter Full Name', max_length=255)),
                ('organization', models.CharField(help_text='Enter your Organization', max_length=255)),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pay_method', models.ForeignKey(help_text='Choose the pay method', on_delete=django.db.models.deletion.PROTECT, related_name='pay_method', to='general.paymemethod')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals_sponsor', to=settings.AUTH_USER_MODEL, verbose_name='Sponsor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
