# Generated by Django 5.1.5 on 2025-02-04 11:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the amount money', max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_verified', models.BooleanField(default=False, editable=False)),
                ('phone_number', models.CharField(help_text='Enter lake this Call number +998 99 999 99 99', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number', regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('new', 'New'), ('moderated', 'Moderated'), ('verified', 'Verified'), ('canceled', 'Canceled')], default='new', max_length=25)),
                ('full_name', models.CharField(help_text='Please enter Full Name', max_length=255)),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Appeal',
            },
        ),
    ]
