# Generated by Django 5.1.5 on 2025-01-28 12:07

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Enter the amount money', max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(help_text='Enter lake this Call number +998 99 999 99 99', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number', regex='^\\+998\\d{9}$')])),
                ('full_name', models.CharField(help_text='Please enter Full Name', max_length=255)),
                ('organization', models.CharField(help_text='Enter your Organization', max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
