# Generated by Django 5.1.5 on 2025-01-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeals', '0001_initial'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsors.studentsponsor'),
        ),
    ]
