# Generated by Django 5.1.6 on 2025-02-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_initial'),
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='pay_method',
            field=models.ForeignKey(help_text='Choose the pay method', on_delete=django.db.models.deletion.PROTECT, related_name='appeal_pay_method', to='general.paymemethod'),
        ),
    ]
