# Generated by Django 5.1.5 on 2025-02-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='full_name',
        ),
    ]
